language: node_js
node_js:
  - "stable"
install: npm install

services:
  - postgresql

cache:
  directories:
    - "node_modules"

addons:
    code_climate:
        repo_token: 205b460fb18d22d3db847cb98cc3fbbee316a0624d59024b5e15728eb78ef38e

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: npm run test

after_success:
  - npm run coverage
